export const operators = {
  if: "si",
  switch: "cambiar",
  while: "mientras",
  try: "intentar",
  print: "imprimir",
  else: "otro",
  break: "romper",
  continue: "continuar",
  return: "regresar",
  catch: "capturar",
  throw: "lanzar",
  public: "publico",
  private: "privado",
  static: "estatico",
  final: "finalizacion",
  "+": "suma",
  "-": "resta",
  "*": "multiplicación",
  "/": "división",
  "^": "Potencia",
  "==": "iguala",
  "!=": "distinto de",
  "<": "es menor que",
  ">": "es mayor que",
  "<=": "es menor o igual que",
  ">=": "es mayor o igual que",
  "{": "entonces",
  "}": "fin",
  "(": "inicio",
  ")": "fin",
};

// export const instructions = {
//   if: "si",
//   switch: "cambiar",
//   while: "mientras",
//   try: "intentar",
//   print: "imprimir",
//   else: "otro",
//   break: "romper",
//   continue: "continuar",
//   return: "regresar",
//   catch: "capturar",
//   throw: "lanzar",
//   public: "publico",
//   private: "privado",
//   static: "estatico",
//   final: "finalizacion",
// };
