export const PALABRAS_RESERVADAS_CONDICION = {
  if: "si",
  switch: "cambiar",
  while: "mientras",
  try: "intentar",
  print: "imprimir",
};
export const PALABRAS_RESERVADAS = {
  else: "otro",
  break: "romper",
  continue: "continuar",
  return: "regresar",
  catch: "capturar",
  throw: "lanzar",
  public: "publico",
  private: "privado",
  static: "estatico",
  final: "final",
  "+": "suma",
  "-": "resta",
  "*": "multiplicación",
  "/": "división",
  "^": "Potencia",
  "==": "Iguala",
  "!=": "Distintode",
  "<": "Menorque",
  "<=": "Menoroigualque",
  ">": "Mayor que",
  ">=": "Mayoroigualque",
};
